version: 2

project_name: ftl

builds:
  - id: ftl
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/yarlson/ftl/cmd.version={{.Version}}

archives:
  - id: release_archive
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

release:
  github:
    owner: yarlson
    name: ftl
  draft: true

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

brews:
  - name: ftl
    repository:
      owner: yarlson
      name: homebrew-ftl
    url_template: "https://github.com/yarlson/ftl/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: Yar Kravtsov
      email: yarlson@gmail.com
    homepage: "https://github.com/yarlson/ftl"
    description: "FTL - Faster Than Light deployment tool"
    license: "MIT"
    test: |
      system "#{bin}/ftl --version"
    install: |
      bin.install "ftl"
